---
require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "test/fixtures/*"

Style/Documentation:
  Exclude:
    - "test/**"

Style/StringLiterals:
  EnforcedStyle: double_quotes
